"""GitHub PR Comment utilities."""
from __future__ import annotations
import html


class CommentFormatter:
    """Formats content for GitHub PR comments."""

    @staticmethod
    def format_analysis(analysis: str) -> str:
        """Format LLM analysis as a markdown comment block.

        All LLM content is HTML-escaped to prevent injection attacks.
        """
        safe_analysis = html.escape(analysis, quote=True)
        return f"""<details>
<summary>AFT Rule Analysis</summary>

{safe_analysis}
</details>"""

    @staticmethod
    def format_test_results(name: str, passed: int, failed: int, duration_ms: float) -> str:
        """Format test results summary."""
        status = "✅" if failed == 0 else "❌"
        safe_name = html.escape(name, quote=True)
        return f"""
## Test Results {status}

| Metric | Value |
|--------|-------|
| Suite | {safe_name} |
| Passed | {passed} |
| Failed | {failed} |
| Duration | {duration_ms:.0f}ms |
"""

    @staticmethod
    def build_full_comment(analysis: str, test_results: str, test_code: str = "") -> str:
        """Build the complete PR comment.

        analysis is HTML-escaped; test_code is wrapped in a code block
        so markdown handles formatting safely.
        """
        safe_analysis = html.escape(analysis, quote=True)
        parts = [
            "## AFT (Agent For Testing)\n",
            f"### Rule Analysis\n{safe_analysis}\n",
            f"### Test Results\n{test_results}\n",
        ]
        if test_code:
            # Code blocks are safe in markdown; escape triple backticks
            safe_code = test_code.replace("```", "\\`\\`\\`")
            parts.append(f"### Generated Test Code\n```python\n{safe_code}\n```\n")
        parts.append("---\n*AI-generated by AFT. Review carefully before merging.*")
        return "".join(parts)
