"""GitHub PR Comment utilities."""
from __future__ import annotations


class CommentFormatter:
    """Formats content for GitHub PR comments."""

    @staticmethod
    def format_analysis(analysis: str) -> str:
        """Format LLM analysis as a markdown comment block."""
        return f"""<details>
<summary>AFT Rule Analysis</summary>

{analysis}
</details>"""

    @staticmethod
    def format_test_results(name: str, passed: int, failed: int, duration_ms: float) -> str:
        """Format test results summary."""
        status = "✅" if failed == 0 else "❌"
        return f"""
## Test Results {status}

| Metric | Value |
|--------|-------|
| Suite | {name} |
| Passed | {passed} |
| Failed | {failed} |
| Duration | {duration_ms:.0f}ms |
"""

    @staticmethod
    def build_full_comment(analysis: str, test_results: str, test_code: str = "") -> str:
        """Build the complete PR comment."""
        parts = [
            "## AFT (Agent For Testing)\n",
            f"### Rule Analysis\n{analysis}\n",
            f"### Test Results\n{test_results}\n",
        ]
        if test_code:
            parts.append(f"### Generated Test Code\n```python\n{test_code}\n```\n")
        parts.append("---\n*AI-generated by AFT. Review carefully before merging.*")
        return "".join(parts)