"""Builds test cases from policy rule descriptions."""
from __future__ import annotations
from aft.engine.plugins.types import TestCase, TestSuite
from aft.llm.prompts.test_generator import TestGeneratorPrompt


class TestBuilder:
    """Builds test cases from rule descriptions using LLM."""

    def __init__(self, llm_client=None):
        self.llm_client = llm_client
        self.prompt_builder = TestGeneratorPrompt()

    def build_from_rule(self, rule_description: str, count: int = 5) -> TestSuite:
        """Build a test suite from a rule description.

        If llm_client is provided, uses LLM to generate tests.
        Otherwise, returns a basic template suite.
        """
        if self.llm_client is None:
            return self._build_basic_suite(rule_description, count)

        # Use LLM to generate tests
        prompt = self.prompt_builder.build(
            rule_description=rule_description,
            test_count=count,
        )
        response = self.llm_client.complete(prompt=prompt)
        return self._parse_llm_response(response.content, rule_description)

    def _build_basic_suite(self, rule_description: str, count: int) -> TestSuite:
        """Build a basic suite without LLM (for testing scaffolding)."""
        suite = TestSuite(metadata={"rule": rule_description, "source": "template"})
        for i in range(min(count, 3)):
            tc = TestCase(
                name=f"test_policy_case_{i + 1}",
                description=f"Test case {i + 1} for: {rule_description}",
                code=f"assert True, '{rule_description}'",
                expected_outcome="pass",
                category="policy",
            )
            suite.add(tc)
        return suite

    def _parse_llm_response(self, llm_output: str, rule_description: str) -> TestSuite:
        """Parse LLM output into a TestSuite."""
        # Simple parsing: look for python code blocks
        suite = TestSuite(metadata={"rule": rule_description, "source": "llm"})
        import re
        code_blocks = re.findall(r'```python\n(.*?)```', llm_output, re.DOTALL)
        if not code_blocks:
            code_blocks = re.findall(r'```\n(.*?)```', llm_output, re.DOTALL)

        if code_blocks:
            all_code = '\n'.join(code_blocks)
            func_names = re.findall(r'def (test_\w+)\(', all_code)
            for name in func_names:
                tc = TestCase(
                    name=name,
                    description=f"Generated by AFT for: {rule_description}",
                    code=all_code,
                    expected_outcome="pass",
                    category="policy",
                )
                suite.add(tc)
        else:
            # Fallback: create a single placeholder test
            suite.add(TestCase(
                name="test_policy_auto_generated",
                description=f"AFT generated test for: {rule_description}",
                code=llm_output,
                expected_outcome="pass",
                category="policy",
            ))
        return suite
