# src/aft/cli.py
"""AFT CLI — command-line interface for CI gate and report generation."""
from __future__ import annotations
import sys
import os

# Ensure src is in path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import click
import yaml
from pathlib import Path

from aft.alert.ci_gate import CIGate
from aft.report.generator import ReportGenerator, ReportType
from aft.cli.router import DiffRouter
from aft.cli.parsers.lint import LintResultParser
from aft.cli.github import GitHubCommentPoster
from aft.cli.analyzers.rule import SkillRuleAnalyzer
from aft.cli.analyzers.content import SkillContentAnalyzer


def load_config() -> dict:
    """Load AFT configuration from config/default.yaml."""
    config_path = Path(__file__).parent.parent / "config" / "default.yaml"
    if not config_path.exists():
        return {}
    with open(config_path) as f:
        return yaml.safe_load(f) or {}


@click.group()
def cli():
    """AFT CLI — Agent For Testing command-line tools."""
    pass


def build_skill_harness_comment(diff_result, lint_results, rule_analysis, content_analysis) -> str:
    """Build the PR comment markdown for Skill-Harness."""
    lines = ["## AFT (Agent For Testing)\n"]

    # Change Analysis section
    if diff_result.change_types:
        lines.append("### Change Analysis\n")
        rows = []
        if diff_result.rule_changes:
            for rc in diff_result.rule_changes:
                summary = next((a.get("change_summary", "") for a in rule_analysis if a.get("rule_id") == rc.rule_id), "")
                rows.append(f"| Rule | `{rc.rule_id}` | {summary} |")
        if diff_result.skill_changes:
            for sc in diff_result.skill_changes:
                summary = next((a.get("change_summary", "") for a in content_analysis if a.get("skill_name") == sc.skill_name), "")
                rows.append(f"| Skill | `{sc.skill_name}` | {summary} |")
        if diff_result.code_changes:
            for cc in diff_result.code_changes:
                rows.append(f"| Code | `{cc.file_path}` | implementation change |")

        if rows:
            lines.append("| Type | File | Summary |\n|--------|-------|\n")
            lines.extend(rows)
        lines.append("")

    # Lint Results section
    total_blockers = sum(len(lr.blockers) for lr in lint_results)
    total_warnings = sum(len(lr.warnings) for lr in lint_results)
    total_hints = sum(len(lr.hints) for lr in lint_results)
    overall_passed = total_blockers == 0

    lines.append("### Lint Results\n\n")
    lines.append("| Level | Count |\n|--------|-------|\n")
    lines.append(f"| Blockers | {total_blockers} | {'✅' if overall_passed else '❌'} |\n")
    lines.append(f"| Warnings | {total_warnings} |\n")
    lines.append(f"| Hints | {total_hints} |\n\n")

    # Rule Change Analysis section
    if rule_analysis:
        lines.append("### Rule Change Analysis\n")
        for analysis in rule_analysis:
            rule_id = analysis.get("rule_id", "?")
            lines.append(f"**{rule_id}**\n")
            lines.append(f"- Summary: {analysis.get('change_summary', 'N/A')}\n")
            lines.append(f"- Risk: {analysis.get('risk_assessment', 'N/A')}\n")
            compat = analysis.get("backward_compatible", None)
            if compat is not None:
                lines.append(f"- Backward compatible: {'yes' if compat else 'no'}\n")
            lines.append("")

    lines.append("---\n")
    lines.append("*AI-generated by AFT. Review carefully before merging.*\n")

    return "".join(lines)


@cli.command("post-comment")
@click.option("--diff", required=True, help="Combined unified diff")
@click.option("--lint-report", required=True, help="Path to lint JSON/JSONL file")
@click.option("--pr", required=True, type=int, help="PR number")
@click.option("--repo", required=True, help="Repository (owner/repo)")
@click.option("--token", default=None, help="GitHub token (or set GITHUB_TOKEN env)")
def post_comment_command(diff: str, lint_report: str, pr: int, repo: str, token: str):
    """Post an AFT quality comment to a GitHub PR.

    Analyzes combined diff + lint results and posts a quality comment.
    Used by GitHub Actions in Skill-Harness repos.
    """
    # Resolve token
    github_token = token or os.environ.get("GITHUB_TOKEN")
    if not github_token:
        click.echo("Error: --token required or GITHUB_TOKEN env not set", err=True)
        sys.exit(1)

    # Parse diff
    router = DiffRouter(diff)
    diff_result = router.route()

    # Parse lint results
    lint_results = LintResultParser.parse_jsonl_file(lint_report)

    # LLM analysis (if we have a real LLM client)
    rule_analysis = []
    content_analysis = []

    try:
        from aft.llm.client import LLMClient
        llm_client = LLMClient()

        rule_analyzer = SkillRuleAnalyzer(llm_client=llm_client)
        for rc in diff_result.rule_changes:
            analysis = rule_analyzer.analyze(rule_diff=rc.diff, rule_id=rc.rule_id)
            rule_analysis.append(analysis)

        content_analyzer = SkillContentAnalyzer(llm_client=llm_client)
        for sc in diff_result.skill_changes:
            # Find matching lint report
            matching_lint = next((lr for lr in lint_results if sc.skill_name in lr.skill_path), None)
            analysis = content_analyzer.analyze(
                skill_diff=sc.diff,
                skill_name=sc.skill_name,
                lint_report=matching_lint,
            )
            content_analysis.append(analysis)
    except Exception as e:
        click.echo(f"Warning: LLM analysis failed: {e}", err=True)

    # Build PR comment
    comment = build_skill_harness_comment(
        diff_result=diff_result,
        lint_results=lint_results,
        rule_analysis=rule_analysis,
        content_analysis=content_analysis,
    )

    # Post to GitHub
    poster = GitHubCommentPoster(token=github_token, repo=repo)
    success = poster.post_comment(pr_number=pr, body=comment)

    if success:
        click.echo(f"Comment posted to PR #{pr}")
    else:
        click.echo(f"Failed to post comment to PR #{pr}", err=True)
        sys.exit(1)


@cli.command("ci-check")
@click.option("--pr", required=True, type=int, help="PR number")
@click.option("--repo", required=True, help="Repository (owner/repo)")
def ci_check_command(pr: int, repo: str):
    """Run CI quality gate check for a PR.

    Returns exit code 0 if CI passes, 1 if CI should block.
    """
    config = load_config()
    gate_config = config.get("ci_gate", {})

    gate = CIGate(config=gate_config)
    result = gate.check(pr_number=pr, repo=repo)

    click.echo(result.reason)

    if result.passed:
        sys.exit(0)
    else:
        sys.exit(1)


@cli.command("report")
@click.option("--type", "report_type", required=True,
              type=click.Choice(["daily", "weekly", "on-demand", "pr-closed"]),
              help="Type of report to generate")
@click.option("--prs", help="Comma-separated PR numbers (for on-demand)")
@click.option("--pr", "single_pr", type=int, help="Single PR number (for pr-closed)")
@click.option("--output", default="stdout",
              help="Output channels: stdout,slack,feishu (comma-separated)")
def report_command(report_type: str, prs: str, single_pr: int, output: str):
    """Generate a quality report.

    Types:
      daily       - Daily aggregation report
      weekly      - Weekly report with week-over-week comparison
      on-demand   - Report for specific PR numbers
      pr-closed   - Quality summary for a single closed PR
    """
    config = load_config()

    from aft.observability.store import ObservabilityStore
    from aft.observability.trends import TrendCalculator

    store = ObservabilityStore(data_dir=config.get("observability", {}).get("data_dir", "data"))
    trend_calc = TrendCalculator(
        coverage_warn_threshold=config.get("observability", {}).get("coverage_warn_threshold", 0.70)
    )

    gen = ReportGenerator(obs_store=store, trend_calc=trend_calc)

    rt = ReportType(report_type)

    if rt == ReportType.ON_DEMAND:
        pr_list = [int(p.strip()) for p in prs.split(",")] if prs else []
        report = gen.generate(rt, prs=pr_list)
    elif rt == ReportType.PR_CLOSED:
        if not single_pr:
            click.echo("Error: --pr required for pr-closed report", err=True)
            sys.exit(1)
        report = gen.generate(rt, pr=single_pr)
    else:
        report = gen.generate(rt)

    # Output
    if "stdout" in output:
        click.echo(f"# {report.title}")
        click.echo(report.rendered)

    channels = [c.strip() for c in output.split(",") if c.strip() not in ("stdout",)]

    if channels and not report.trend:
        click.echo("No trend data to send to channels", err=True)
        return

    if "slack" in channels and config.get("alert", {}).get("slack_webhook_url"):
        from aft.alert.channels.slack import SlackNotifier
        notifier = SlackNotifier(webhook_url=config["alert"]["slack_webhook_url"])
        pr_info = {
            "pr_number": single_pr or report.metadata.get("pr", "?"),
            "repo": config.get("observability", {}).get("repo", "?"),
            "pr_url": f"https://github.com/{config.get('observability', {}).get('repo', '?')}/pull/{single_pr or '?'}",
        }
        notifier.send(trend=report.trend, pr_info=pr_info)

    if "feishu" in channels and config.get("alert", {}).get("feishu_webhook_url"):
        from aft.alert.channels.feishu import FeishuNotifier
        notifier = FeishuNotifier(webhook_url=config["alert"]["feishu_webhook_url"])
        pr_info = {
            "pr_number": single_pr or report.metadata.get("pr", "?"),
            "repo": config.get("observability", {}).get("repo", "?"),
            "pr_url": f"https://github.com/{config.get('observability', {}).get('repo', '?')}/pull/{single_pr or '?'}",
        }
        notifier.send(trend=report.trend, pr_info=pr_info)


if __name__ == "__main__":
    cli()