# tests/unit/test_post_comment_command.py
"""Tests for post-comment CLI command and build_skill_harness_comment."""
import pytest
import json
import tempfile
from unittest.mock import patch, MagicMock
from click.testing import CliRunner
import sys
import importlib
import importlib.util

# We need to import from cli.py which is a module file, not the cli/ package
# Approach: Load cli.py into a fake module, then copy its attributes to the real cli package

# First, ensure the cli package submodules are loaded
from aft.cli.router import DiffRouter, DiffRouterResult, RuleFileChange, SkillFileChange, CodeChange
from aft.cli.parsers.lint import LintResultParser, LintReport, LintResult
from aft.cli.github import GitHubCommentPoster

# Now save the cli package module
_cli_package = sys.modules.get('aft.cli')

# Remove the cli package temporarily
if 'aft.cli' in sys.modules:
    del sys.modules['aft.cli']

# Load cli.py as a fresh module
_cli_path = '/Users/lijingnan/Desktop/project/test_haress_engine/aft/src/aft/cli.py'
_spec = importlib.util.spec_from_file_location('_cli_module', _cli_path)
_cli_module = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_cli_module)

# Now we need to make aft.cli point to _cli_module
# But we also need to ensure that 'from aft.cli.router import X' still works
# So we need to merge _cli_module's attributes into _cli_package

if _cli_package is not None:
    # Copy all attributes from _cli_module to _cli_package
    for attr in dir(_cli_module):
        if not attr.startswith('_'):
            setattr(_cli_package, attr, getattr(_cli_module, attr))
    # Restore sys.modules['aft.cli'] to the package
    sys.modules['aft.cli'] = _cli_package
else:
    # No existing package, just use the module
    sys.modules['aft.cli'] = _cli_module

# Extract what we need from the module
build_skill_harness_comment = _cli_module.build_skill_harness_comment
post_comment_command = _cli_module.post_comment_command
cli = _cli_module.cli


class TestBuildSkillHarnessComment:
    """Tests for build_skill_harness_comment function."""

    def test_build_comment_with_empty_results(self):
        """Build comment with no diff results or lint results."""
        diff_result = DiffRouterResult(
            rule_changes=[],
            skill_changes=[],
            code_changes=[],
            change_types=[],
        )

        comment = build_skill_harness_comment(
            diff_result=diff_result,
            lint_results=[],
            rule_analysis=[],
            content_analysis=[],
        )

        assert "## AFT (Agent For Testing)" in comment
        assert "### Lint Results" in comment
        assert "Blockers | 0 | ✅" in comment
        assert "*AI-generated by AFT" in comment

    def test_build_comment_with_rule_changes(self):
        """Build comment with rule changes and analysis."""
        diff_result = DiffRouterResult(
            rule_changes=[
                RuleFileChange(rule_id="exec-001", diff="...", changed_fields=["level"])
            ],
            change_types=["rule"],
        )

        rule_analysis = [{
            "rule_id": "exec-001",
            "change_summary": "severity lowered",
            "risk_assessment": "low",
            "backward_compatible": True,
        }]

        comment = build_skill_harness_comment(
            diff_result=diff_result,
            lint_results=[],
            rule_analysis=rule_analysis,
            content_analysis=[],
        )

        assert "exec-001" in comment
        assert "severity lowered" in comment
        assert "### Change Analysis" in comment
        assert "### Rule Change Analysis" in comment

    def test_build_comment_with_skill_changes(self):
        """Build comment with skill changes."""
        diff_result = DiffRouterResult(
            skill_changes=[
                SkillFileChange(skill_name="pdf", diff="...", file_path="fixtures/canonical-skills/pdf.md")
            ],
            change_types=["skill"],
        )

        content_analysis = [{
            "skill_name": "pdf",
            "change_summary": "added new examples",
            "content_quality": "improved",
        }]

        comment = build_skill_harness_comment(
            diff_result=diff_result,
            lint_results=[],
            rule_analysis=[],
            content_analysis=content_analysis,
        )

        assert "pdf" in comment
        assert "added new examples" in comment
        assert "### Change Analysis" in comment

    def test_build_comment_with_code_changes(self):
        """Build comment with code changes."""
        diff_result = DiffRouterResult(
            code_changes=[
                CodeChange(file_path="src/lint/rules/exec-001.ts", diff="...")
            ],
            change_types=["code"],
        )

        comment = build_skill_harness_comment(
            diff_result=diff_result,
            lint_results=[],
            rule_analysis=[],
            content_analysis=[],
        )

        assert "exec-001.ts" in comment
        assert "implementation change" in comment

    def test_build_comment_with_lint_blockers(self):
        """Build comment with lint blockers (failed lint)."""
        diff_result = DiffRouterResult(
            skill_changes=[
                SkillFileChange(skill_name="test", diff="...", file_path="test.md")
            ],
            change_types=["skill"],
        )

        lint_report = LintReport(
            skill_path="test.md",
            skill_name="test",
            overall_passed=False,
            blockers=[
                LintResult(rule_id="struct-001", message="Missing frontmatter", level="BLOCKER"),
            ],
            warnings=[],
            hints=[],
        )

        comment = build_skill_harness_comment(
            diff_result=diff_result,
            lint_results=[lint_report],
            rule_analysis=[],
            content_analysis=[],
        )

        assert "Blockers | 1 | ❌" in comment
        assert "Warnings | 0" in comment

    def test_build_comment_with_lint_warnings_and_hints(self):
        """Build comment with lint warnings and hints."""
        lint_report = LintReport(
            skill_path="test.md",
            skill_name="test",
            overall_passed=True,
            blockers=[],
            warnings=[
                LintResult(rule_id="exec-003", message="directory name mismatch", level="WARNING"),
            ],
            hints=[
                LintResult(rule_id="style-001", message="code block language", level="HINT"),
            ],
        )

        comment = build_skill_harness_comment(
            diff_result=DiffRouterResult(),
            lint_results=[lint_report],
            rule_analysis=[],
            content_analysis=[],
        )

        assert "Blockers | 0 | ✅" in comment
        assert "Warnings | 1" in comment
        assert "Hints | 1" in comment

    def test_build_comment_with_multiple_rule_changes(self):
        """Build comment with multiple rule changes."""
        diff_result = DiffRouterResult(
            rule_changes=[
                RuleFileChange(rule_id="exec-001", diff="...", changed_fields=["level"]),
                RuleFileChange(rule_id="exec-002", diff="...", changed_fields=["description"]),
            ],
            change_types=["rule"],
        )

        rule_analysis = [
            {
                "rule_id": "exec-001",
                "change_summary": "severity lowered",
                "risk_assessment": "low",
                "backward_compatible": True,
            },
            {
                "rule_id": "exec-002",
                "change_summary": "description updated",
                "risk_assessment": "medium",
                "backward_compatible": False,
            },
        ]

        comment = build_skill_harness_comment(
            diff_result=diff_result,
            lint_results=[],
            rule_analysis=rule_analysis,
            content_analysis=[],
        )

        assert "exec-001" in comment
        assert "exec-002" in comment
        assert "severity lowered" in comment
        assert "description updated" in comment
        assert "### Rule Change Analysis" in comment

    def test_build_comment_with_mixed_changes(self):
        """Build comment with rule, skill, and code changes."""
        diff_result = DiffRouterResult(
            rule_changes=[
                RuleFileChange(rule_id="exec-001", diff="...", changed_fields=["level"])
            ],
            skill_changes=[
                SkillFileChange(skill_name="pdf", diff="...", file_path="fixtures/canonical-skills/pdf.md")
            ],
            code_changes=[
                CodeChange(file_path="src/lint/rules/exec-001.ts", diff="...")
            ],
            change_types=["rule", "skill", "code"],
        )

        comment = build_skill_harness_comment(
            diff_result=diff_result,
            lint_results=[],
            rule_analysis=[],
            content_analysis=[],
        )

        assert "### Change Analysis" in comment
        assert "Rule" in comment
        assert "Skill" in comment
        assert "Code" in comment


class TestPostCommentCommand:
    """Tests for post_comment_command CLI command."""

    def test_post_comment_command_exists(self):
        """Post-comment command should be registered."""
        assert "post-comment" in cli.commands

    def test_post_comment_requires_token(self):
        """Exit with code 1 when no token provided and GITHUB_TOKEN not set."""
        with tempfile.NamedTemporaryFile(mode='w', suffix='.jsonl', delete=False) as f:
            f.write('{"skillPath": "test.md", "skillName": "test", "overallPassed": true, "blockers": [], "warnings": [], "hints": [], "timestamp": "2026-04-19T10:00:00Z"}\n')
            lint_file = f.name

        try:
            with patch.dict("os.environ", {}, clear=True):
                runner = CliRunner()
                result = runner.invoke(post_comment_command, [
                    "--diff", "--- a/test.md\n+++ b/test.md",
                    "--lint-report", lint_file,
                    "--pr", "2341",
                    "--repo", "owner/repo",
                ])

            assert result.exit_code == 1
            assert "GITHUB_TOKEN env not set" in result.output
        finally:
            import os
            os.unlink(lint_file)
